### PR TITLE
upgrade: swap clorox for turbocolor

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hi @yviscool, thank you for using clorox! I've deprecated the pkg a while ago so this PR upgrades you to its latest incarnation, [turbocolor](https://github.com/jorgebucaran/turbocolor), which is lighter and faster. In addition, we don't need to coerce strings, and as a result of that, the coloring code has become a bit simpler.

Let me know if this looks good to you!

### CODE REVIEW

**Comment by yviscool** [comment]
Thanks @jorgebucaran ,

**Comment by jorgebucaran** [comment]
Thank you, @yviscool! If you can publish a new version that would be great. There are no breaking changes to your library so I suggest a patch bump.

**Comment by yviscool** [comment]
I will publish  soon, thank you again @jorgebucaran

**Comment by jorgebucaran** [comment]
Cheers! 🎉

**Pull request merged**
